GET http://localhost:1337/api/persons

GET http://localhost:1337/api/persons/65b2f308a634faf757a8debb



POST http://localhost:1337/api/persons
Content-Type: application/json
{
    "name": "Holga Kilgore",
    "number": "1337x"
}

POST http://localhost:1337/api/persons
Content-Type: application/json
{
    "name": "Shelock Holmes",
    "number": "221B"
}

POST http://localhost:1337/api/persons
Content-Type: application/json
{
    "name": "John Doe",
    "number": "339"
}

POST http://localhost:1337/api/persons
Content-Type: application/json
{
    "name": "Gold Eagle Actual",
    "number": "17589"
}

POST http://localhost:1337/api/persons
Content-Type: application/json
{
    "name": "Bravo Six",
    "number": "2189448"
}

POST http://localhost:1337/api/persons
Content-Type: application/json
{
    "name": "Kilo one Actual",
    "number": "124589"
}

POST http://localhost:1337/api/persons
Content-Type: application/json
{
    "name": "Outlaw two five",
    "number": "17589"
}

POST http://localhost:1337/api/persons
Content-Type: application/json
{
    "name": "Deadly four Niner",
    "number": "17589"
}

POST http://localhost:1337/api/persons
Content-Type: application/json
{
    "name": "Hunter One",
    "number": "17232589"
}

POST http://localhost:1337/api/persons
Content-Type: application/json
{
    "name": "Damon Salvatore",
    "number": "17239589"
}

POST http://localhost:1337/api/persons
Content-Type: application/json
{
    "name": "Mongoose two",
    "number": "17589"
}

POST http://localhost:1337/api/persons
Content-Type: application/json
{
    "number": "17589"
}

POST http://localhost:1337/api/persons
Content-Type: application/json


DELETE  http://localhost:1337/api/persons/65b2f308a634faf757a8debb

DELETE  http://localhost:1337/api/persons/65b2f31a1dfb830f3bcfaf93
