GET http://localhost:1337/api/blogs

GET http://localhost:1337/api/users

DELETE   http://localhost:1337/api/blogs/65bd35030de4d45a036b6606

POST http://localhost:1337/api/blogs
Content-Type: application/json
{
    "author": "Holga Kilgore",
    "url": "https://github.com/Itsfoss0",
    "title": "Getting good at git"
}

POST http://localhost:1337/api/blogs
Content-Type: application/json
{
    "author": "Taylor Shaw",
    "url": "https://learnk8s.io",
    "title": "Kubernetes Ingress"
}

POST http://localhost:1337/api/blogs
Content-Type: application/json
{
    "author": "Robert Greene",
    "url": "https://foo.bar.baz",
    "title": "Foo Bar"
}

PUT  http://localhost:1337/api/blogs/65b66a44436d1a52803238a8
Content-Type: application/json
{
    "author": "Sherlock Holmes",
    "url": "itsfoss0.hashnode.dev",
    "title": "What is systemd",
    "likes": 3
}

POST http://localhost:1337/api/blogs
Content-Type: application/json
{
    "author": "Jane Doe",
    "title": "Docker compose for all"
}


GET http://localhost:1337/api/users/65bc08cb86e63fc001a12191

POST http://localhost:1337/api/users
Content-Type: application/json
{
    "username": "holgaK",
    "name": "Holga Kilgore",
    "password": "holga"
}

POST http://localhost:1337/api/users
Content-Type: application/json
{
    "username": "sherlock",
    "name": "Sherlock Holmes",
    "password": "sholmes"
}

POST http://localhost:1337/api/users
Content-Type: application/json
{
    "username":"D",
    "name": "Go",
    "password": "bravosix"
}

POST http://localhost:1337/api/auth/login
Content-Type: application/json
{
    "username": "eagleG",
    "password": "bravosix"
}